version: "3"

includes:
  aqua: lib/aqua
  aws: lib/aws
  components: lib/components
  mixins: lib/mixins
  snaplet: lib/snaplet
  terraform:
    taskfile: lib/terraform
    aliases: [tf]
  toolbox: lib/toolbox

tasks: {}
