version: "3"

includes:
  aqua: lib/aqua
  aws: lib/aws
  components: lib/components
  cursor: lib/cursor
  mixins: lib/mixins
  os: lib/os-modules
  snaplet: lib/snaplet
  tf:
    taskfile: lib/tf
  toolbox: lib/toolbox

tasks: {}
